BM Review and Search
brianfroschauer/book-in pull request #17
Opened 2020-09-08 22:15 UTC by katiacammisa

# Description

Modify and Delete Review
Search Book by title and Author by name

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How has this been tested?

Please describe the tests that you ran to verify your changes.

- [X] Automation testing (Unit or integration tests)
- [X] Manual testing (Postman)

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] My pull request is up to date with develop

2020-09-08 22:24 UTC, brianfroschauer requested changes

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/controller/BookController.java
> +                                @Spec(path = "title", spec = Like.class)})
No se podría agregar dentro de la especificación?

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/dto/review/ReviewDTO.java
> +    private boolean edited;
esto pertenece a la tarea del search? no habíamos quedado en que haya una fecha de edición en lugar del boolean?

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/dto/review/UpdateReviewDTO.java
> +    private Integer stars; /* Using Integer because int can't be null */
Perfecto! borremos el comentario nomas

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/entity/Review.java
> +    private boolean edited;
```java
@Column(name = "updated_at")
private Date updatedAt;
```

Si es nulo nunca fue editado, si hay una fecha, sabemos cuando se editó

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/service/review/ReviewServiceImpl.java
> +                    if (review.getStars() != 0) old.setStars(review.getStars());
podría ser 0 alguna vez? dado que en el DTO validamos que sea entre 1 y 5. Si el check está demas, borrarlo

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
Por qué cambiamos a like?

2020-09-08 22:24 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/specification/BookSpecification.java
> +        @Spec(path = "genre", spec = Like.class),
Like? no debería ser equals?

2020-09-08 22:25 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
La idea es que desde el front hagan /authors?key="Kati" y se devuelvan todos los autores cuyo Nombre o apellido matchean con Kati

2020-09-08 22:27 UTC, katiacammisa commented on src/main/java/com/austral/bookin/controller/BookController.java
> +                                @Spec(path = "title", spec = Like.class)})
El tema es que la especificación del book tiene también filtrado por genero e idioma. Por lo que hable con Diego antes de que llegaras la idea acá es filtrar solamente por titulo, por eso lo hice aparte.

2020-09-08 22:28 UTC, katiacammisa commented on src/main/java/com/austral/bookin/dto/review/ReviewDTO.java
> +    private boolean edited;
Tenes razón, no me di cuenta que la fecha era null si nunca lo editaron. Pense que la setteabamos cuando se creaba

2020-09-08 22:29 UTC, katiacammisa commented on src/main/java/com/austral/bookin/service/review/ReviewServiceImpl.java
> +                    if (review.getStars() != 0) old.setStars(review.getStars());
Cuando no le pasas estrellas en el UpdateReviewDTO, el model mapper le asigna el valor 0 en vez de null. Por eso es el chequeo.

2020-09-08 22:31 UTC, katiacammisa commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
Por lo que vi en las user stories si pongo /authors?firstName=at me debería devolver todos los autores cuyos firstName contengan "at". Tipo eso me devolvería Kati y Mati ponele. En cambio con el Equal sería un match perfecto hasta donde entiendo.

2020-09-08 22:32 UTC, katiacammisa commented on src/main/java/com/austral/bookin/specification/BookSpecification.java
> +        @Spec(path = "genre", spec = Like.class),
Same del otro

2020-09-08 22:39 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
Claro, en la user story dice que es un like?

2020-09-08 22:40 UTC, katiacammisa commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
No esta escrito pero en el wireframe se ve eso. Y fue lo que le pregunte a Diego también

2020-09-08 22:40 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
Cuando buscas por firstName es un equal, pero cuando buscas por el param key es un like de firstName y lastName

2020-09-08 22:43 UTC, katiacammisa commented on src/main/java/com/austral/bookin/specification/AuthorSpecification.java
> +        @Spec(path = "lastName", spec = Like.class),
Osea hago 2 métodos distintos? Bah no sé si hay alguna forma de hacer eso en un solo método pero me suena raro. Ahi estoy viendo como implementar lo de la key

2020-09-10 02:30 UTC, brianfroschauer requested changes

2020-09-10 02:30 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/controller/AuthorController.java
> +                                    @Spec(path = "lastName", params = "key", spec = Like.class)})
Por que quedó esto así? no quedó el search aparte al final?

2020-09-10 02:30 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/controller/BookController.java
> +                                @Spec(path = "title", params = "key", spec = Like.class)})
idem, no me gusta mucho tener un objeto para la especificación y aparte meter los Specs acá

2020-09-10 02:30 UTC, brianfroschauer commented on src/main/java/com/austral/bookin/service/review/ReviewServiceImpl.java
> +                    if (review.getStars() != 0) old.setStars(review.getStars());
Ahh okok

2020-09-11 00:40 UTC, merged